#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Jul 21 21:31:57 2017

@author: david
"""

from mpl_toolkits.basemap import Basemap
import matplotlib.pyplot as plt

map = Basemap()

map.drawcoastlines()

map.etopo()

x, y = map(14, 43)

map.plot(x, y, marker='o',color='m')

plt.show()

x, y = map(157, -8)

map.plot(x, y, marker='o',color='m')

plt.show()

x, y = map(27, 39)

map.plot(x, y, marker='D',color='r')

plt.show()

x, y = map(-80, 0)

map.plot(x, y, marker='o',color='m')

plt.show()

map.drawcountries()

map.drawstates(color='0.5')

x, y = map(-115, 38)

map.plot(x, y, marker='o',color='m')

plt.show()
